### PR TITLE
RFC: Proposed reorganization for automatic signal formatting and implementation of `Sounds` API

### PR DESCRIPTION
**Pull request by haberdashPI**
Whew! Okay... this one is large. Quite a few things here—it should eventually
be broken up—but this was in a place where I wanted to actually discuss what
I've been thinking through.

If this is what SampledSignals ends up looking like I'll have some clean-up and
more testing to do and probably some fixes to make, but I'm pretty convinced
the basic approach is do-able and practical approach at this point. And
all of the original tests that make sense for the new approach (all but
a few) pass locally. This needs a few small updates to LibSndFile
so the tests won't pass on CI.

So the main question is whether this is the right way to go. It would
involve some fairly major changes:

1. I implemented `mapsignals` which applies a function to each sample of
   multiple signals but automatically pads the end of signals and can operate
   over streams, buffers, numbers and any abstract array, automatically
   coercing the objects as necssary. This can be used to implement the most of
   the methods in `Sounds`. This is really the motivating force behind many of
   the below changes and I think the goal should be to have *something* that
   makes this work well.  You can think of the rest of the changes as really a
   proposal for how to make `mapsignals` work.
2. It uses generic, trait-based dispatch to determine the format of a signal.
   The functions `promote_signals(xs...)` and `promote_signal(x,by=y)` inspect
   their objects and call `tosamplerate` and `tochannels` to format the signals
   appropriately. Signals define the latter two functions along with the
   `SignalFormat` trait to participate in the generic interface for signal
   promotion.  
3. The signal formatting is represented by a unitful sample
   rate and bit rate. A spectral signal has a sample rate in time, a temporal
   signal a sample rate in frequency. The bit rate is represented separately
   because it needs to be handled somewhat differently for buffers and streams.
   I tried combining them but it was a bit of a mess and there were lots of
   exceptions
4. SampleBuf can now be used to represent any AbstractArray as a signal: this
   comes in handy when trying to operate over ranges, for instance. It makes
   the generic code to operate over signals with `mapsignals` easier to write.
5. SampleStream has a simplified interface. Rather than specifying the start
   and length it simply takes an abstract array. One can limit the range by
   using a `view` over a larger array. The fact that it's abstract also means
   it can handle channel mixing lazily because I've defined an object that
   mixes the channels on demand.
6. SampleStream doesn't convert the bit rate. Most  functions in julia converts
   bit rates automatically, so most of the logic for same and different bit
   rate code is exactly the same, and converting it before passing it is slow.
   So slow, uncessary work. If necessary it's easy enough to convert the bit
   rate within an implementation that can't be more generic.
7. There are some miscelaneous smaller changes I made, largely to simplify
   and improve my understanding of the code.
8. I added some additional functionally—just to get a sense of what it would
  take to do it—to create signals from functions. As a consequence
  one no longer really neads `SinSource`, as it can be defined as, e.g.
  signal(sin,1kHz). A missing behavior, that would need to be implemented
  is to combine signals into multiple channels, e.g. something like `channels(signal(sin,1kHz,phase=0),signal(sin,1kHz,phase=pi))`.

NOTE:  I'm not sure `mapsignals` can easily be separated into another
	package. We were originally thinking `Sounds` functions for
	manipulating sounds would be in another package. However, `mapsignals` has to somehow generate a
	signal which, to be non-specific to this package, would require
	recreating the broadcast machinery ala `broadcast_similar` and friends
	and defining an interface for reading and writing to signals that looks
	a *lot* like the interface for `SampleSource` and `SampleSink`... so
	why not just use those, and other packages that want to implement
	signals that work with this machinery can just ensure their objects are
	coercable to sources or sinks. I already have defined `tosource` to
	coerce to sources, and it would be easy to also have `tosink` as well.

### CODE REVIEW

**Comment by haberdashPI** [comment]
One thing I realized I forgot to mention about `SampleBuf`'s new design:

My thinking was that, in this approach, to design a new kind of sample-buffer-like object with different behaviors you simply wrap some `AbstractArray` object in a `SampleBuf` using `signal(myobject,sr)`. If you need to specialize the behavior of this new type you can specialize dispatch over `SampleBuf{<:MyType}`. There is never a need to create a child type of `SampleBuf` or worry about what the other type parameters of `SampleBuf` are.

**Comment by haberdashPI** [comment]
Another point that has occurred to me about this is that the resulting `SampleBuf` looks a lot more like the format for `AxisArray`: it might well make sense to just *use* `AxisArray` types and eliminate `SampleBuf` entirely, ala #38, only defining the `SampleSink` and `SampleSource` objects.

That said, having though about it more, I kind of like having `+` and `*` defined to mean the same thing as `mix` and `amplify`, and this would only make sense if there was a specific `SampleBuf` type, and would not make so much sense for `AxisArray` objects. (And `AxisArrays` could easily participate in `mapsignals`: it would not be hard to define `SignalFormat(x::AxisArray)` and friends).

**Comment by ssfrr** [comment]
Hello. Big apologies for ghosting on this.

I haven't been able to go through in detail, but here're some initial thoughts:
> I implemented mapsignals which applies a function to each sample of multiple signals

Is this equivalent to `map(fn, zip(sig1, sig2))`? If so I wonder if the padding/resampling/channel mixing behavior could be added to some new methods of `zip` rather than introducing a new function. I guess one issue would be threading the samplerate info through, because `fn` would be operating on individual samples and by default `map` would just collect them into a `Vector`, but maybe `zip` would return some kind of `SignalIterator` or something that would provide the samples of the signals, and then a `map(::Function, ::SignalIterator` method would apply the right samplerate to the result signal.

>  kind of like having + and * defined to mean the same thing as mix and amplify

I don't really like `*` as `amplify`, because `SampleBuf`s should still behave as `Vector`s, and vector-vector multiplication doesn't work. The operation should be `.*` to pointwise multiply signals, but because that is handled by the broadcast machinery we can't just define a `.*` method (I think?). One idea would be to hook into broadcasting to do the automatic length extension. I haven't thought enough about exactly how that would work, but it seems like it might let us take advantage of more `AbstractArray` fallback handling where all the broadcasted operations work as expected but with the additional length extension as necessary.

> SampleStream has a simplified interface. Rather than specifying the start and length it simply takes an abstract array

Yeah, this is something I've actually been meaning to do as well. Originally I did it this way to make it possible to define zero-allocating `unsafe_read!` methods, but it's much less convenient and not worth it.

> A spectral signal has a sample rate in time, a temporal signal a sample rate in frequency

I had it this way in an earlier iteration rather than separate types, but I think that dealing with dispatching on the type parameters was a hassle. That might not apply anymore given the other architectural changes you've made, so I'm definitely open to this.

> the resulting SampleBuf looks a lot more like the format for AxisArray: it might well make sense to just use AxisArray

I _think_ that there's value to having these types more focused on time and frequency-domain signals, and not have to worry about generalized units. It lets us make more assumptions about use-cases.

> to design a new kind of sample-buffer-like object with different behaviors you simply wrap some `AbstractArray` object in a SampleBuf using `signal(myobject,sr)`

I'm a little worried that `signal` is already used for the FRP-inspired libraries like Reactive and Signals, and it wouldn't be surprising for a user to be using both of them (e.g. creating a bunch of sliders that you map to audio parameters). That said, it's a good name, and maybe it's OK if user's have to qualify the name when they coexist. If we do go that direction, it's worth thinking about whether we can go all-in and read and write `Signal`s from `SignalSource`s and `SignalSink`s. Especially given the time-frequency unification `Signal` makes sense, and is definitely snappier than `SampleBuf`. And it's still in the package name. :)

That's all I can get into for now, but I'll think on this a little more and try to find some time to get more familiar with the code. Thanks for putting all the work into this! We'll get it sorted eventually...

**Comment by ssfrr** [comment]
thinking about it a little more, I think your `mapsignals` is sometimes called `lift` (e.g. in the Elm language, but it seems they've moved away from that terminology).

**Comment by haberdashPI** [comment]
>  If we do go that direction, it's worth thinking about whether we can go all-in and read and write Signals from SignalSources and SignalSinks.

**Comment by haberdashPI** [comment]
So... there are a number of orthogonal issues here. Having gone through the work of trying to implement this, I think I have a much better sense of a road map of how to proceed. Here's a proposed roadmap:

**Comment by haberdashPI** [comment]
Oh! I just realized, I think there *is* a way to implement `mapsignals` as a specialization of `broadcast`. I've been learning more about the ways to customize this machinery with another package I'm working on to create a generic `MetaArray` that maintains the broadcast behavior of the array it wraps. I think if we override `copyto!`, `copy` and `instantiate` we can select the shape of the array based on all the arguments using `instantiate`, and then call the default broadcast machinery on each of the subparts of the array.

**Comment by haberdashPI** [comment]
So I think there are a few orthogonal issues, which maybe can be separated into separate pull requests. Now that I've worked on all of the parts I think I have a better idea of how to best separate these out.

1. The changes in the implementation to `SampleBuf` and `SpectrumBuf` to one type and the changes to their interface: I think this is in someways the most disruptive change, and the one that is the least settled. Thus, it might be worth hashing out the merit of this separately from the other changes, and since a lot of how I got `mapsignals` working was to start with these changes, it seems like the place to start. This pull request would define the `Signal` trait (or whatever it's name becomes... `SignalTrait`, `SignalFormat`?).

2. The changes and simplifications in the interface and implementation of `SampleSink` and `SampleSource`. Seems like we're mostly on the same page here, baring the formatting information being stored in the type, which we'll hopefully have figured out, one way or another, in the pull request for change 1.

3. The implementation of `mapsignals` or the specialization of `broadcast` to support padding. I think if specializing `broadcast` works, the issue of mapping `mix` and `amplify` to `+` and `*` is pretty moot.

4. Name changes, and the introduction of `signal` method (or whatever it becomes). Once we've mostly worked out what the changes in 1 and 2 look like, then maybe we can hash out the names, once it's clear what there is to be named.

This would mean losing some functionality along the way, as we figure out how each part works, but it seems like a good way of breaking down what needs to be worked out into smaller parts.

**Comment by haberdashPI** [comment]
Ha! Sorry, I keep thinking of new things. I think it is worth trying to extend broadcast, to see if it works: once the other pieces are in place: one can define two new broadcast styles. One for buffers alone and another that includes at least one stream. Then, by overriding `copyto!` and `copy` for streams, these can call the broadcasting machinery, lazily, on each chunk that's read out.

**Comment by haberdashPI** [comment]
Hi @ssfrr, just checking in on this again, I haven't committed any time to this because it wasn't clear whether this is was the direction you wanted to see `SampledSignals` take or not.

**Comment by ssfrr** [comment]
Yeah, that's probably the smart move. I'm trying to limit how much time I spend on things that are not shortest-path to finishing my dissertation, and this big reorganization isn't something that I have much time for.

As an aside, I've been doing a little reworking of Ogg.jl and Opus.jl to handle streaming, and have had pretty good results with an `iterate`-based API that gives `Tuple`s of samples. Performance seems quite good, so whenever I get around to digging into this more I'm strongly considering ditching the `read`/`write` streaming for iterating over frames. Unfortunately that probably complicates rather than simplifies this discussion, but that's where my head is at right now.

**Comment by haberdashPI** [comment]
Aye, yes, by all means, focus on the dissertation! Best wishes!

I've wondered about an `iterate` interface: one thing I like about the `read/write` option is that it allows more flexibility when retrieving the block: although maybe I misunderstand your point: are you saying the iterate operates sample-by-sample?

I think what I'll do for know then is refine an approach for the `buffer` case, and not worry *too* much about streams at the moment, since it isn't what I need myself. I'll probably publish that as part of a public `Sounds.jl` library. (Obviously I'll give you credit, since I'll be building on what I made here based on my integration of Sounds and SampledSignals). Perhaps at some point later on, we can unify the interfaces.

**Comment by ssfrr** [comment]
yes, `iterate` operates sample-by-sample (or frame-by-frame for multichannel). What sort of flexibility does `read`/`write` give that you find useful?

**Comment by haberdashPI** [comment]
If it's sample-by-sample my point about flexibility is moot. I would thinking you iterated block-by-block (in which case, the `read/write` option allows you to specify how large each block is).

**Comment by haberdashPI** [comment]
One point that occurs to me is that the two interfaces are inter-operable: you should be able to implement the one with the other. So that might mean that if I work on the general functions I'd like to have (e.g. `ramp` etc...) using the `read/write` interface as an assumption, that could be implemented by a sample source implemented using the `iterate` interface. So it might not be too hard to integrate our work, when/if that makes sense to do.

**Comment by haberdashPI** [comment]
Just an FYI: I've implemented my various operations as proposed in this PR in the package [SignalOperators](https://github.com/haberdashPI/SignalOperators.jl), which should interoperate fairly well with both `SampleBuf` objects and `AxisArrays` objects (and soon with arrays from the [`DimensionalData`](https://github.com/rafaqz/DimensionalData.jl) package). @rob-luke, I know you were interested in this. I would welcome any feedback.

**Pull request closed without merging**
